### ISSUE TITLE
Mac paths does not include `/Users/<username>/Applications`

### ISSUE THREAD

**Issue by jrop** [cerebroapp/cerebro-basic-apps#1]
Hi, I had created KeliON/cerebro#286 because I have disabled spotlight on my Mac, and since your latest release, I have disabled "mac-apps" and gone with using "basic-apps", which works fine.  However, there is one path that the plugin is not searching on my Mac:

`/Users/<username>/Applications/*.app`

In my user Applications folder, I have several apps that I have created with Automator etc., and it would be nice to be able to launch these with Cerebro.

Thanks again!

**Comment by KELiON** [comment]
@jrop done!

**Comment by jrop** [comment]
That solved it, thank you much!
