### ISSUE TITLE
Command or Command R button won't load up application in Finder

### ISSUE THREAD

**Issue by siddhero97** [cerebroapp/cerebro-basic-apps#3]
In Readme.md#features, it is said that when you press Command you should receive the Application in finder. But this is not the case.

**Comment by KELiON** [comment]
@siddhero97 good, in this plugin only <kbd>ctrl+r</kbd> used to work, I've fixed it in v1.0.9. 

BTW: if you use this plugin on Mac and spotlight index does work on your machine, it is recommended to use [mac-apps](https://github.com/KELiON/cerebro-mac-apps) plugin
