### ISSUE TITLE
Support *.desktop entries marked with `Terminal=true`

### ISSUE THREAD

**Issue by max-baz** [cerebroapp/cerebro-basic-apps#5]
Basically when there is a property `Terminal=true`, instead of running `<Exec-command>` as a separate process, Cerebro has to run `<terminal> -e <Exec-command>`. Sounds easy, the difficult part is to determine what is the terminal that user is using. There is simply no way to detect it. Some window managers provide their custom ways to do so, but even so there is a huge variety of window managers doing so in different ways.

I can only think of actually making this a plugin setting, where users themselves define the name of their terminal application.

**Comment by ogustavo-pereira** [comment]
This suggestion is interesting, today is not a priority for our team. If you're interested in raising any PR, I'll keep it open until next month.

**Comment by max-baz** [comment]
I am no longer using cerebro so won't be sending a PR, but glad to hear you guys are picking up the project! 😉

**Comment by ogustavo-pereira** [comment]
Thanks for the reply, I will close this issue, feel free to open it again if you use it again
